GDP:
  NY.GDP.MKTP.CD

GDP_PER_CAPITA:
  NY.GDP.PCAP.CD

INFLATION:
  FP.CPI.TOTL.ZG

DEBT:
  DT.DOD.PVLX.CD

DEBT_SERVICE:
  DT.TDS.DECT.GN.ZS

EXCHANGE_RATE:

MINIMUM_WAGE:

HEALTH_EXPENDITURE_PER_CAPITA:
  SH.XPD.CHEX.PC.CD

HEALTH_EXPENDITURE_IN_GDP:
  SH.XPD.CHEX.GD.ZS

HOSPITAL_BEDS_PER_1000:
  SH.MED.BEDS.ZS

PHYSICIANS_PER_1000:
  SH.MED.PHYS.ZS

NURSES_AND_MIDWIVES_PER_1000:
  SH.MED.NUMW.P3

COMMUNITY_HEALTH_WORKERS_PER_1000:
  SH.MED.CMHW.P3

COUNTRIES:
- JAP
- CAN
- GER
- FRA
- USA

INDICATORS:
- NY.GDP.MKTP.CD
- NY.GDP.PCAP.CD
- FP.CPI.TOTL.ZG
- DT.DOD.PVLX.CD
- DT.TDS.DECT.GN.ZS

BUCKET_NAME:
  "economic-data-landing"


