[pytest]
markers =
    unit: marks test as unit tests
    new: marks test as new feature tests
    integration: marks tests as integration tests
    regression: marks tests as regression tests
    slow: marks tests as slow
    fast: marks tests as fast