name: Pipeline Test in Dev and UAT

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "uat" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create .env file
      run: | 
        echo ACCESS_SECRET=${{ secrets.ACCESS_SECRET }} >> .env 
        echo ACCESS_KEY=${{ secrets.ACCESS_KEY }} >> .env

    - name: Format Scripts in test and src
      run: |
        black src
        black tests

    - name: Lint with Ruff
      run: |
        python -m ruff check src/ tests/ 

    - name: Run Sync ETL file
      run: |
        echo "running python src/etl.py"

    - name: Test with pytest
      run: |
        echo "Starting tests..."
